### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by Shmalle** [lambdagit101/lambdapse#3]
I want to start the bot after installing the dependencies but I cant since I dont know how to input the token.

**Comment by lambdagit101** [comment]
you do not put it in the config
if on linux, do `export BOT_TOKEN="your bot's token"` before starting the bot
or make a new file called .env (try .env. on windows) and put BOT_TOKEN="your bot's token" inside it

**Comment by lambdagit101** [comment]
sorry for replying too goddamn late
i don't check github often these days
